### ISSUE TITLE
displayed query string have wrong parameters representation.

### ISSUE THREAD

**Issue by SemyenSoldatenko** [7digital/oauth-reference-page#2]
Query string displayed on page is not valid, (query parameters are not escaped).
But signature looks correct.
I think this line is wrong.
https://github.com/7digital/oauth-reference-page/blob/gh-pages/oauth.js#L37

**Comment by minkaotic** [comment]
Hi Semyon! 
Good catch - and apologies for the slow response. I was hoping to get around to fixing this sooner and respond to you then, but things have been a bit wild at work the last few months. We'll hopefully get a chance to fix this some time soon, but if you're up for submitting a PR, that would certainly help to speed things up. 
Thanks for flagging this!

**Comment by danjamesmay** [comment]
Query strings and POST body representations should now be encoded correctly.

For the query string, this is to conform to [RFC3986](https://tools.ietf.org/html/rfc3986), the standard for URI's.

For the post body, this is to comply with section [3.4.1.3.1](https://tools.ietf.org/html/rfc5849#section-3.4.1.3.1) of the OAuth1.0 spec, which requires post body parameters to be encoded as [application/x-www-form-urlencoded](https://www.w3.org/TR/html401/interact/forms.html#h-17.13.4.1).

They are basically the same, except form-encoding requires a '+' to represent a SPACE.
